import { Box, Typography } from '@mui/material'
import CoorIconButtonNew from './CoorIconButtonNew'

const CoorIconButtons = () => {
	return (
		<Box
			sx={{ padding: '10px' }}
			gap={'5px'}
			display={'flex'}
			flexDirection={'column'}
		>
			<Typography variant="sys.typo.h2">Main Buttons</Typography>
			<Box
				gap={'5px'}
				display={'flex'}
				flexDirection={'row'}
			>
				<CoorIconButtonNew
					intensity="high"
					color="custom"
					customColor="magenta"
					size="h4"
					iconName="help"
				/>
				<CoorIconButtonNew
					intensity="high"
					color="custom"
					customColor="magenta"
					size="h4"
					iconName="help"
					forceHover
				/>

				<CoorIconButtonNew
					intensity="high"
					color="custom"
					customColor="magenta"
					size="h4"
					iconName="help"
					active
				/>
				<CoorIconButtonNew
					intensity="high"
					color="custom"
					customColor="magenta"
					size="h4"
					iconName="help"
					disabled
				/>
			</Box>
			<Box
				gap={'5px'}
				display={'flex'}
				flexDirection={'row'}
			>
				<CoorIconButtonNew
					intensity="medium"
					color="main"
					size="h4"
					iconName="help"
				/>
				<CoorIconButtonNew
					intensity="medium"
					color="main"
					size="h4"
					iconName="help"
					forceHover
				/>

				<CoorIconButtonNew
					intensity="medium"
					color="main"
					size="h4"
					iconName="help"
					active
				/>
				<CoorIconButtonNew
					intensity="medium"
					color="main"
					size="h4"
					iconName="help"
					disabled
				/>
			</Box>
			<Box
				gap={'5px'}
				display={'flex'}
				flexDirection={'row'}
			>
				<CoorIconButtonNew
					intensity="low"
					color="main"
					size="h4"
					iconName="help"
				/>
				<CoorIconButtonNew
					intensity="low"
					color="main"
					size="h4"
					iconName="help"
					forceHover
				/>

				<CoorIconButtonNew
					intensity="low"
					color="main"
					size="h4"
					iconName="help"
					active
				/>
				<CoorIconButtonNew
					intensity="low"
					color="main"
					size="h4"
					iconName="help"
					disabled
				/>
			</Box>
			<Box
				gap={'5px'}
				display={'flex'}
				flexDirection={'row'}
			>
				<CoorIconButtonNew
					intensity="lowest"
					color="main"
					size="h4"
					iconName="help"
				/>
				<CoorIconButtonNew
					intensity="lowest"
					color="main"
					size="h4"
					iconName="help"
					forceHover
				/>

				<CoorIconButtonNew
					intensity="lowest"
					color="main"
					size="h4"
					iconName="help"
					active
				/>
				<CoorIconButtonNew
					intensity="lowest"
					color="main"
					size="h4"
					iconName="help"
					disabled
				/>
			</Box>
			<Box
				gap={'5px'}
				display={'flex'}
				flexDirection={'row'}
			>
				<CoorIconButtonNew
					intensity="outline"
					color="main"
					size="h4"
					iconName="help"
				/>
				<CoorIconButtonNew
					intensity="outline"
					color="main"
					size="h4"
					iconName="help"
					forceHover
				/>

				<CoorIconButtonNew
					intensity="outline"
					color="main"
					size="h4"
					iconName="help"
					active
				/>
				<CoorIconButtonNew
					intensity="outline"
					color="main"
					size="h4"
					iconName="help"
					disabled
				/>
			</Box>
			<Box
				gap={'5px'}
				display={'flex'}
				flexDirection={'row'}
			>
				<CoorIconButtonNew
					intensity="invert"
					color="main"
					size="h4"
					iconName="help"
				/>
				<CoorIconButtonNew
					intensity="invert"
					color="main"
					size="h4"
					iconName="help"
					forceHover
				/>

				<CoorIconButtonNew
					intensity="invert"
					color="main"
					size="h4"
					iconName="help"
					active
				/>
				<CoorIconButtonNew
					intensity="invert"
					color="main"
					size="h4"
					iconName="help"
					disabled
				/>
			</Box>
			<Box
				gap={'5px'}
				display={'flex'}
				flexDirection={'row'}
			>
				<CoorIconButtonNew
					intensity="high"
					color="main"
					size="t1"
					iconName="help"
				/>
				<CoorIconButtonNew
					intensity="high"
					color="main"
					size="t1"
					iconName="help"
					forceHover
				/>

				<CoorIconButtonNew
					intensity="high"
					color="main"
					size="t1"
					iconName="help"
					active
				/>
				<CoorIconButtonNew
					intensity="high"
					color="main"
					size="t1"
					iconName="help"
					disabled
				/>
			</Box>
			<Box
				gap={'5px'}
				display={'flex'}
				flexDirection={'row'}
			>
				<CoorIconButtonNew
					intensity="medium"
					color="main"
					size="t1"
					iconName="help"
				/>
				<CoorIconButtonNew
					intensity="medium"
					color="main"
					size="t1"
					iconName="help"
					forceHover
				/>

				<CoorIconButtonNew
					intensity="medium"
					color="main"
					size="t1"
					iconName="help"
					active
				/>
				<CoorIconButtonNew
					intensity="medium"
					color="main"
					size="t1"
					iconName="help"
					disabled
				/>
			</Box>
			<Box
				gap={'5px'}
				display={'flex'}
				flexDirection={'row'}
			>
				<CoorIconButtonNew
					intensity="low"
					color="main"
					size="t1"
					iconName="help"
				/>
				<CoorIconButtonNew
					intensity="low"
					color="main"
					size="t1"
					iconName="help"
					forceHover
				/>

				<CoorIconButtonNew
					intensity="low"
					color="main"
					size="t1"
					iconName="help"
					active
				/>
				<CoorIconButtonNew
					intensity="low"
					color="main"
					size="t1"
					iconName="help"
					disabled
				/>
			</Box>
			<Box
				gap={'5px'}
				display={'flex'}
				flexDirection={'row'}
			>
				<CoorIconButtonNew
					intensity="lowest"
					color="main"
					size="t1"
					iconName="help"
				/>
				<CoorIconButtonNew
					intensity="lowest"
					color="main"
					size="t1"
					iconName="help"
					forceHover
				/>

				<CoorIconButtonNew
					intensity="lowest"
					color="main"
					size="t1"
					iconName="help"
					active
				/>
				<CoorIconButtonNew
					intensity="lowest"
					color="main"
					size="t1"
					iconName="help"
					disabled
				/>
			</Box>
			<Box
				gap={'5px'}
				display={'flex'}
				flexDirection={'row'}
			>
				<CoorIconButtonNew
					intensity="outline"
					color="main"
					size="t1"
					iconName="help"
				/>
				<CoorIconButtonNew
					intensity="outline"
					color="main"
					size="t1"
					iconName="help"
					forceHover
				/>

				<CoorIconButtonNew
					intensity="outline"
					color="main"
					size="t1"
					iconName="help"
					active
				/>
				<CoorIconButtonNew
					intensity="outline"
					color="main"
					size="t1"
					iconName="help"
					disabled
				/>
			</Box>
			<Box
				gap={'5px'}
				display={'flex'}
				flexDirection={'row'}
			>
				<CoorIconButtonNew
					intensity="invert"
					color="main"
					size="t1"
					iconName="help"
				/>
				<CoorIconButtonNew
					intensity="invert"
					color="main"
					size="t1"
					iconName="help"
					forceHover
				/>

				<CoorIconButtonNew
					intensity="invert"
					color="main"
					size="t1"
					iconName="help"
					active
				/>
				<CoorIconButtonNew
					intensity="invert"
					color="main"
					size="t1"
					iconName="help"
					disabled
				/>
			</Box>
			<Box
				gap={'5px'}
				display={'flex'}
				flexDirection={'row'}
			>
				<CoorIconButtonNew
					intensity="high"
					color="main"
					size="st1"
					iconName="help"
				/>
				<CoorIconButtonNew
					intensity="high"
					color="main"
					size="st1"
					iconName="help"
					forceHover
				/>

				<CoorIconButtonNew
					intensity="high"
					color="main"
					size="st1"
					iconName="help"
					active
				/>
				<CoorIconButtonNew
					intensity="high"
					color="main"
					size="st1"
					iconName="help"
					disabled
				/>
			</Box>
			<Box
				gap={'5px'}
				display={'flex'}
				flexDirection={'row'}
			>
				<CoorIconButtonNew
					intensity="medium"
					color="main"
					size="st1"
					iconName="help"
				/>
				<CoorIconButtonNew
					intensity="medium"
					color="main"
					size="st1"
					iconName="help"
					forceHover
				/>

				<CoorIconButtonNew
					intensity="medium"
					color="main"
					size="st1"
					iconName="help"
					active
				/>
				<CoorIconButtonNew
					intensity="medium"
					color="main"
					size="st1"
					iconName="help"
					disabled
				/>
			</Box>
			<Box
				gap={'5px'}
				display={'flex'}
				flexDirection={'row'}
			>
				<CoorIconButtonNew
					intensity="low"
					color="main"
					size="st1"
					iconName="help"
				/>
				<CoorIconButtonNew
					intensity="low"
					color="main"
					size="st1"
					iconName="help"
					forceHover
				/>

				<CoorIconButtonNew
					intensity="low"
					color="main"
					size="st1"
					iconName="help"
					active
				/>
				<CoorIconButtonNew
					intensity="low"
					color="main"
					size="st1"
					iconName="help"
					disabled
				/>
			</Box>
			<Box
				gap={'5px'}
				display={'flex'}
				flexDirection={'row'}
			>
				<CoorIconButtonNew
					intensity="lowest"
					color="main"
					size="st1"
					iconName="help"
				/>
				<CoorIconButtonNew
					intensity="lowest"
					color="main"
					size="st1"
					iconName="help"
					forceHover
				/>

				<CoorIconButtonNew
					intensity="lowest"
					color="main"
					size="st1"
					iconName="help"
					active
				/>
				<CoorIconButtonNew
					intensity="lowest"
					color="main"
					size="st1"
					iconName="help"
					disabled
				/>
			</Box>
			<Box
				gap={'5px'}
				display={'flex'}
				flexDirection={'row'}
			>
				<CoorIconButtonNew
					intensity="outline"
					color="main"
					size="st1"
					iconName="help"
				/>
				<CoorIconButtonNew
					intensity="outline"
					color="main"
					size="st1"
					iconName="help"
					forceHover
				/>

				<CoorIconButtonNew
					intensity="outline"
					color="main"
					size="st1"
					iconName="help"
					active
				/>
				<CoorIconButtonNew
					intensity="outline"
					color="main"
					size="st1"
					iconName="help"
					disabled
				/>
			</Box>
			<Box
				gap={'5px'}
				display={'flex'}
				flexDirection={'row'}
			>
				<CoorIconButtonNew
					intensity="invert"
					color="main"
					size="st1"
					iconName="help"
				/>
				<CoorIconButtonNew
					intensity="invert"
					color="main"
					size="st1"
					iconName="help"
					forceHover
				/>

				<CoorIconButtonNew
					intensity="invert"
					color="main"
					size="st1"
					iconName="help"
					active
				/>
				<CoorIconButtonNew
					intensity="invert"
					color="main"
					size="st1"
					iconName="help"
					disabled
				/>
			</Box>
			<Typography variant="sys.typo.h2">Success Buttons</Typography>
			<Box
				gap={'5px'}
				display={'flex'}
				flexDirection={'row'}
			>
				<CoorIconButtonNew
					intensity="high"
					color="success"
					size="h4"
					iconName="help"
				/>
				<CoorIconButtonNew
					intensity="high"
					color="success"
					size="h4"
					iconName="help"
					forceHover
				/>

				<CoorIconButtonNew
					intensity="high"
					color="success"
					size="h4"
					iconName="help"
					active
				/>
				<CoorIconButtonNew
					intensity="high"
					color="success"
					size="h4"
					iconName="help"
					disabled
				/>
			</Box>
			<Box
				gap={'5px'}
				display={'flex'}
				flexDirection={'row'}
			>
				<CoorIconButtonNew
					intensity="medium"
					color="success"
					size="h4"
					iconName="help"
				/>
				<CoorIconButtonNew
					intensity="medium"
					color="success"
					size="h4"
					iconName="help"
					forceHover
				/>

				<CoorIconButtonNew
					intensity="medium"
					color="success"
					size="h4"
					iconName="help"
					active
				/>
				<CoorIconButtonNew
					intensity="medium"
					color="success"
					size="h4"
					iconName="help"
					disabled
				/>
			</Box>
			<Box
				gap={'5px'}
				display={'flex'}
				flexDirection={'row'}
			>
				<CoorIconButtonNew
					intensity="low"
					color="success"
					size="h4"
					iconName="help"
				/>
				<CoorIconButtonNew
					intensity="low"
					color="success"
					size="h4"
					iconName="help"
					forceHover
				/>

				<CoorIconButtonNew
					intensity="low"
					color="success"
					size="h4"
					iconName="help"
					active
				/>
				<CoorIconButtonNew
					intensity="low"
					color="success"
					size="h4"
					iconName="help"
					disabled
				/>
			</Box>
			<Box
				gap={'5px'}
				display={'flex'}
				flexDirection={'row'}
			>
				<CoorIconButtonNew
					intensity="lowest"
					color="success"
					size="h4"
					iconName="help"
				/>
				<CoorIconButtonNew
					intensity="lowest"
					color="success"
					size="h4"
					iconName="help"
					forceHover
				/>

				<CoorIconButtonNew
					intensity="lowest"
					color="success"
					size="h4"
					iconName="help"
					active
				/>
				<CoorIconButtonNew
					intensity="lowest"
					color="success"
					size="h4"
					iconName="help"
					disabled
				/>
			</Box>
			<Box
				gap={'5px'}
				display={'flex'}
				flexDirection={'row'}
			>
				<CoorIconButtonNew
					intensity="outline"
					color="success"
					size="h4"
					iconName="help"
				/>
				<CoorIconButtonNew
					intensity="outline"
					color="success"
					size="h4"
					iconName="help"
					forceHover
				/>

				<CoorIconButtonNew
					intensity="outline"
					color="success"
					size="h4"
					iconName="help"
					active
				/>
				<CoorIconButtonNew
					intensity="outline"
					color="success"
					size="h4"
					iconName="help"
					disabled
				/>
			</Box>

			<Box
				gap={'5px'}
				display={'flex'}
				flexDirection={'row'}
			>
				<CoorIconButtonNew
					intensity="high"
					color="success"
					size="t1"
					iconName="help"
				/>
				<CoorIconButtonNew
					intensity="high"
					color="success"
					size="t1"
					iconName="help"
					forceHover
				/>

				<CoorIconButtonNew
					intensity="high"
					color="success"
					size="t1"
					iconName="help"
					active
				/>
				<CoorIconButtonNew
					intensity="high"
					color="success"
					size="t1"
					iconName="help"
					disabled
				/>
			</Box>
			<Box
				gap={'5px'}
				display={'flex'}
				flexDirection={'row'}
			>
				<CoorIconButtonNew
					intensity="medium"
					color="success"
					size="t1"
					iconName="help"
				/>
				<CoorIconButtonNew
					intensity="medium"
					color="success"
					size="t1"
					iconName="help"
					forceHover
				/>

				<CoorIconButtonNew
					intensity="medium"
					color="success"
					size="t1"
					iconName="help"
					active
				/>
				<CoorIconButtonNew
					intensity="medium"
					color="success"
					size="t1"
					iconName="help"
					disabled
				/>
			</Box>
			<Box
				gap={'5px'}
				display={'flex'}
				flexDirection={'row'}
			>
				<CoorIconButtonNew
					intensity="low"
					color="success"
					size="t1"
					iconName="help"
				/>
				<CoorIconButtonNew
					intensity="low"
					color="success"
					size="t1"
					iconName="help"
					forceHover
				/>

				<CoorIconButtonNew
					intensity="low"
					color="success"
					size="t1"
					iconName="help"
					active
				/>
				<CoorIconButtonNew
					intensity="low"
					color="success"
					size="t1"
					iconName="help"
					disabled
				/>
			</Box>
			<Box
				gap={'5px'}
				display={'flex'}
				flexDirection={'row'}
			>
				<CoorIconButtonNew
					intensity="lowest"
					color="success"
					size="t1"
					iconName="help"
				/>
				<CoorIconButtonNew
					intensity="lowest"
					color="success"
					size="t1"
					iconName="help"
					forceHover
				/>

				<CoorIconButtonNew
					intensity="lowest"
					color="success"
					size="t1"
					iconName="help"
					active
				/>
				<CoorIconButtonNew
					intensity="lowest"
					color="success"
					size="t1"
					iconName="help"
					disabled
				/>
			</Box>
			<Box
				gap={'5px'}
				display={'flex'}
				flexDirection={'row'}
			>
				<CoorIconButtonNew
					intensity="outline"
					color="success"
					size="t1"
					iconName="help"
				/>
				<CoorIconButtonNew
					intensity="outline"
					color="success"
					size="t1"
					iconName="help"
					forceHover
				/>

				<CoorIconButtonNew
					intensity="outline"
					color="success"
					size="t1"
					iconName="help"
					active
				/>
				<CoorIconButtonNew
					intensity="outline"
					color="success"
					size="t1"
					iconName="help"
					disabled
				/>
			</Box>

			<Box
				gap={'5px'}
				display={'flex'}
				flexDirection={'row'}
			>
				<CoorIconButtonNew
					intensity="high"
					color="success"
					size="st1"
					iconName="help"
				/>
				<CoorIconButtonNew
					intensity="high"
					color="success"
					size="st1"
					iconName="help"
					forceHover
				/>

				<CoorIconButtonNew
					intensity="high"
					color="success"
					size="st1"
					iconName="help"
					active
				/>
				<CoorIconButtonNew
					intensity="high"
					color="success"
					size="st1"
					iconName="help"
					disabled
				/>
			</Box>
			<Box
				gap={'5px'}
				display={'flex'}
				flexDirection={'row'}
			>
				<CoorIconButtonNew
					intensity="medium"
					color="success"
					size="st1"
					iconName="help"
				/>
				<CoorIconButtonNew
					intensity="medium"
					color="success"
					size="st1"
					iconName="help"
					forceHover
				/>

				<CoorIconButtonNew
					intensity="medium"
					color="success"
					size="st1"
					iconName="help"
					active
				/>
				<CoorIconButtonNew
					intensity="medium"
					color="success"
					size="st1"
					iconName="help"
					disabled
				/>
			</Box>
			<Box
				gap={'5px'}
				display={'flex'}
				flexDirection={'row'}
			>
				<CoorIconButtonNew
					intensity="low"
					color="success"
					size="st1"
					iconName="help"
				/>
				<CoorIconButtonNew
					intensity="low"
					color="success"
					size="st1"
					iconName="help"
					forceHover
				/>

				<CoorIconButtonNew
					intensity="low"
					color="success"
					size="st1"
					iconName="help"
					active
				/>
				<CoorIconButtonNew
					intensity="low"
					color="success"
					size="st1"
					iconName="help"
					disabled
				/>
			</Box>
			<Box
				gap={'5px'}
				display={'flex'}
				flexDirection={'row'}
			>
				<CoorIconButtonNew
					intensity="lowest"
					color="success"
					size="st1"
					iconName="help"
				/>
				<CoorIconButtonNew
					intensity="lowest"
					color="success"
					size="st1"
					iconName="help"
					forceHover
				/>

				<CoorIconButtonNew
					intensity="lowest"
					color="success"
					size="st1"
					iconName="help"
					active
				/>
				<CoorIconButtonNew
					intensity="lowest"
					color="success"
					size="st1"
					iconName="help"
					disabled
				/>
			</Box>
			<Box
				gap={'5px'}
				display={'flex'}
				flexDirection={'row'}
			>
				<CoorIconButtonNew
					intensity="outline"
					color="success"
					size="st1"
					iconName="help"
				/>
				<CoorIconButtonNew
					intensity="outline"
					color="success"
					size="st1"
					iconName="help"
					forceHover
				/>

				<CoorIconButtonNew
					intensity="outline"
					color="success"
					size="st1"
					iconName="help"
					active
				/>
				<CoorIconButtonNew
					intensity="outline"
					color="success"
					size="st1"
					iconName="help"
					disabled
				/>
			</Box>
			<Typography variant="sys.typo.h2">Warning Buttons</Typography>
			<Box
				gap={'5px'}
				display={'flex'}
				flexDirection={'row'}
			>
				<CoorIconButtonNew
					intensity="high"
					color="warning"
					size="h4"
					iconName="help"
				/>
				<CoorIconButtonNew
					intensity="high"
					color="warning"
					size="h4"
					iconName="help"
					forceHover
				/>

				<CoorIconButtonNew
					intensity="high"
					color="warning"
					size="h4"
					iconName="help"
					active
				/>
				<CoorIconButtonNew
					intensity="high"
					color="warning"
					size="h4"
					iconName="help"
					disabled
				/>
			</Box>
			<Box
				gap={'5px'}
				display={'flex'}
				flexDirection={'row'}
			>
				<CoorIconButtonNew
					intensity="medium"
					color="warning"
					size="h4"
					iconName="help"
				/>
				<CoorIconButtonNew
					intensity="medium"
					color="warning"
					size="h4"
					iconName="help"
					forceHover
				/>

				<CoorIconButtonNew
					intensity="medium"
					color="warning"
					size="h4"
					iconName="help"
					active
				/>
				<CoorIconButtonNew
					intensity="medium"
					color="warning"
					size="h4"
					iconName="help"
					disabled
				/>
			</Box>
			<Box
				gap={'5px'}
				display={'flex'}
				flexDirection={'row'}
			>
				<CoorIconButtonNew
					intensity="low"
					color="warning"
					size="h4"
					iconName="help"
				/>
				<CoorIconButtonNew
					intensity="low"
					color="warning"
					size="h4"
					iconName="help"
					forceHover
				/>

				<CoorIconButtonNew
					intensity="low"
					color="warning"
					size="h4"
					iconName="help"
					active
				/>
				<CoorIconButtonNew
					intensity="low"
					color="warning"
					size="h4"
					iconName="help"
					disabled
				/>
			</Box>
			<Box
				gap={'5px'}
				display={'flex'}
				flexDirection={'row'}
			>
				<CoorIconButtonNew
					intensity="lowest"
					color="warning"
					size="h4"
					iconName="help"
				/>
				<CoorIconButtonNew
					intensity="lowest"
					color="warning"
					size="h4"
					iconName="help"
					forceHover
				/>

				<CoorIconButtonNew
					intensity="lowest"
					color="warning"
					size="h4"
					iconName="help"
					active
				/>
				<CoorIconButtonNew
					intensity="lowest"
					color="warning"
					size="h4"
					iconName="help"
					disabled
				/>
			</Box>
			<Box
				gap={'5px'}
				display={'flex'}
				flexDirection={'row'}
			>
				<CoorIconButtonNew
					intensity="outline"
					color="warning"
					size="h4"
					iconName="help"
				/>
				<CoorIconButtonNew
					intensity="outline"
					color="warning"
					size="h4"
					iconName="help"
					forceHover
				/>

				<CoorIconButtonNew
					intensity="outline"
					color="warning"
					size="h4"
					iconName="help"
					active
				/>
				<CoorIconButtonNew
					intensity="outline"
					color="warning"
					size="h4"
					iconName="help"
					disabled
				/>
			</Box>

			<Box
				gap={'5px'}
				display={'flex'}
				flexDirection={'row'}
			>
				<CoorIconButtonNew
					intensity="high"
					color="warning"
					size="t1"
					iconName="help"
				/>
				<CoorIconButtonNew
					intensity="high"
					color="warning"
					size="t1"
					iconName="help"
					forceHover
				/>

				<CoorIconButtonNew
					intensity="high"
					color="warning"
					size="t1"
					iconName="help"
					active
				/>
				<CoorIconButtonNew
					intensity="high"
					color="warning"
					size="t1"
					iconName="help"
					disabled
				/>
			</Box>
			<Box
				gap={'5px'}
				display={'flex'}
				flexDirection={'row'}
			>
				<CoorIconButtonNew
					intensity="medium"
					color="warning"
					size="t1"
					iconName="help"
				/>
				<CoorIconButtonNew
					intensity="medium"
					color="warning"
					size="t1"
					iconName="help"
					forceHover
				/>

				<CoorIconButtonNew
					intensity="medium"
					color="warning"
					size="t1"
					iconName="help"
					active
				/>
				<CoorIconButtonNew
					intensity="medium"
					color="warning"
					size="t1"
					iconName="help"
					disabled
				/>
			</Box>
			<Box
				gap={'5px'}
				display={'flex'}
				flexDirection={'row'}
			>
				<CoorIconButtonNew
					intensity="low"
					color="warning"
					size="t1"
					iconName="help"
				/>
				<CoorIconButtonNew
					intensity="low"
					color="warning"
					size="t1"
					iconName="help"
					forceHover
				/>

				<CoorIconButtonNew
					intensity="low"
					color="warning"
					size="t1"
					iconName="help"
					active
				/>
				<CoorIconButtonNew
					intensity="low"
					color="warning"
					size="t1"
					iconName="help"
					disabled
				/>
			</Box>
			<Box
				gap={'5px'}
				display={'flex'}
				flexDirection={'row'}
			>
				<CoorIconButtonNew
					intensity="lowest"
					color="warning"
					size="t1"
					iconName="help"
				/>
				<CoorIconButtonNew
					intensity="lowest"
					color="warning"
					size="t1"
					iconName="help"
					forceHover
				/>

				<CoorIconButtonNew
					intensity="lowest"
					color="warning"
					size="t1"
					iconName="help"
					active
				/>
				<CoorIconButtonNew
					intensity="lowest"
					color="warning"
					size="t1"
					iconName="help"
					disabled
				/>
			</Box>
			<Box
				gap={'5px'}
				display={'flex'}
				flexDirection={'row'}
			>
				<CoorIconButtonNew
					intensity="outline"
					color="warning"
					size="t1"
					iconName="help"
				/>
				<CoorIconButtonNew
					intensity="outline"
					color="warning"
					size="t1"
					iconName="help"
					forceHover
				/>

				<CoorIconButtonNew
					intensity="outline"
					color="warning"
					size="t1"
					iconName="help"
					active
				/>
				<CoorIconButtonNew
					intensity="outline"
					color="warning"
					size="t1"
					iconName="help"
					disabled
				/>
			</Box>

			<Box
				gap={'5px'}
				display={'flex'}
				flexDirection={'row'}
			>
				<CoorIconButtonNew
					intensity="high"
					color="warning"
					size="st1"
					iconName="help"
				/>
				<CoorIconButtonNew
					intensity="high"
					color="warning"
					size="st1"
					iconName="help"
					forceHover
				/>

				<CoorIconButtonNew
					intensity="high"
					color="warning"
					size="st1"
					iconName="help"
					active
				/>
				<CoorIconButtonNew
					intensity="high"
					color="warning"
					size="st1"
					iconName="help"
					disabled
				/>
			</Box>
			<Box
				gap={'5px'}
				display={'flex'}
				flexDirection={'row'}
			>
				<CoorIconButtonNew
					intensity="medium"
					color="warning"
					size="st1"
					iconName="help"
				/>
				<CoorIconButtonNew
					intensity="medium"
					color="warning"
					size="st1"
					iconName="help"
					forceHover
				/>

				<CoorIconButtonNew
					intensity="medium"
					color="warning"
					size="st1"
					iconName="help"
					active
				/>
				<CoorIconButtonNew
					intensity="medium"
					color="warning"
					size="st1"
					iconName="help"
					disabled
				/>
			</Box>
			<Box
				gap={'5px'}
				display={'flex'}
				flexDirection={'row'}
			>
				<CoorIconButtonNew
					intensity="low"
					color="warning"
					size="st1"
					iconName="help"
				/>
				<CoorIconButtonNew
					intensity="low"
					color="warning"
					size="st1"
					iconName="help"
					forceHover
				/>

				<CoorIconButtonNew
					intensity="low"
					color="warning"
					size="st1"
					iconName="help"
					active
				/>
				<CoorIconButtonNew
					intensity="low"
					color="warning"
					size="st1"
					iconName="help"
					disabled
				/>
			</Box>
			<Box
				gap={'5px'}
				display={'flex'}
				flexDirection={'row'}
			>
				<CoorIconButtonNew
					intensity="lowest"
					color="warning"
					size="st1"
					iconName="help"
				/>
				<CoorIconButtonNew
					intensity="lowest"
					color="warning"
					size="st1"
					iconName="help"
					forceHover
				/>

				<CoorIconButtonNew
					intensity="lowest"
					color="warning"
					size="st1"
					iconName="help"
					active
				/>
				<CoorIconButtonNew
					intensity="lowest"
					color="warning"
					size="st1"
					iconName="help"
					disabled
				/>
			</Box>
			<Box
				gap={'5px'}
				display={'flex'}
				flexDirection={'row'}
			>
				<CoorIconButtonNew
					intensity="outline"
					color="warning"
					size="st1"
					iconName="help"
				/>
				<CoorIconButtonNew
					intensity="outline"
					color="warning"
					size="st1"
					iconName="help"
					forceHover
				/>

				<CoorIconButtonNew
					intensity="outline"
					color="warning"
					size="st1"
					iconName="help"
					active
				/>
				<CoorIconButtonNew
					intensity="outline"
					color="warning"
					size="st1"
					iconName="help"
					disabled
				/>
			</Box>
		</Box>
	)
}

export default CoorIconButtons
