import { Box, Typography } from '@mui/material'
import CoorButton from './CoorButton'

const CoorButtons = () => {
	return (
		<Box
			sx={{ padding: '10px' }}
			gap={'5px'}
			display={'flex'}
			flexDirection={'column'}
		>
			<Typography variant="sys.typo.h2">Custom Buttons</Typography>
			<Box
				gap={'5px'}
				display={'flex'}
				flexDirection={'row'}
			>
				<CoorButton
					intensity="high"
					label="Button"
					color="custom"
					customColor="purple"
					size="st1"
					iconName="help"
					iconPosition="start"
				/>
				<CoorButton
					intensity="high"
					label="Button"
					color="custom"
					customColor="purple"
					size="t1"
					iconName="help"
					iconPosition="end"
					forceHover
				/>
				<CoorButton
					intensity="high"
					label="Button"
					color="custom"
					customColor="purple"
					size="h4"
					forceHover
					iconName="help"
					iconPosition="end"
				/>

				<CoorButton
					intensity="high"
					label="Button"
					color="custom"
					customColor="purple"
					size="h4"
					active
				/>
				<CoorButton
					intensity="high"
					label="Button"
					color="custom"
					customColor="purple"
					size="h4"
					disabled
				/>
			</Box>
			<Box
				gap={'5px'}
				display={'flex'}
				flexDirection={'row'}
			>
				<CoorButton
					intensity="medium"
					label="Button"
					color="custom"
					customColor="purple"
					size="h4"
				/>
				<CoorButton
					intensity="medium"
					label="Button"
					color="custom"
					customColor="purple"
					size="h4"
					forceHover
				/>

				<CoorButton
					intensity="medium"
					label="Button"
					color="custom"
					customColor="purple"
					size="h4"
					active
				/>
				<CoorButton
					intensity="medium"
					label="Button"
					color="custom"
					customColor="purple"
					size="h4"
					disabled
				/>
			</Box>
			<Box
				gap={'5px'}
				display={'flex'}
				flexDirection={'row'}
			>
				<CoorButton
					intensity="invert"
					label="Button"
					color="main"
					size="h4"
					iconName="help"
					iconPosition="start"
				/>
				<CoorButton
					intensity="invert"
					label="Button"
					color="main"
					size="h4"
					forceHover
				/>

				<CoorButton
					intensity="invert"
					label="Button"
					color="main"
					size="h4"
					active
				/>
				<CoorButton
					intensity="invert"
					label="Button"
					color="main"
					size="h4"
					disabled
				/>
			</Box>
			<Box
				gap={'5px'}
				display={'flex'}
				flexDirection={'row'}
			>
				<CoorButton
					intensity="low"
					label="Button"
					color="main"
					size="h4"
				/>
				<CoorButton
					intensity="low"
					label="Button"
					color="main"
					size="h4"
					forceHover
				/>

				<CoorButton
					intensity="low"
					label="Button"
					color="main"
					size="h4"
					active
				/>
				<CoorButton
					intensity="low"
					label="Button"
					color="main"
					size="h4"
					disabled
				/>
			</Box>
			<Box
				gap={'5px'}
				display={'flex'}
				flexDirection={'row'}
			>
				<CoorButton
					intensity="lowest"
					label="Button"
					color="main"
					size="h4"
				/>
				<CoorButton
					intensity="lowest"
					label="Button"
					color="main"
					size="h4"
					forceHover
				/>

				<CoorButton
					intensity="lowest"
					label="Button"
					color="main"
					size="h4"
					active
				/>
				<CoorButton
					intensity="lowest"
					label="Button"
					color="main"
					size="h4"
					disabled
				/>
			</Box>
			<Box
				gap={'5px'}
				display={'flex'}
				flexDirection={'row'}
			>
				<CoorButton
					intensity="outline"
					label="Button"
					color="main"
					size="h4"
				/>
				<CoorButton
					intensity="outline"
					label="Button"
					color="main"
					size="h4"
					forceHover
				/>

				<CoorButton
					intensity="outline"
					label="Button"
					color="main"
					size="h4"
					active
				/>
				<CoorButton
					intensity="outline"
					label="Button"
					color="main"
					size="h4"
					disabled
				/>
			</Box>
			<Typography variant="sys.typo.h2">Main Buttons</Typography>
			<Box
				gap={'5px'}
				display={'flex'}
				flexDirection={'row'}
			>
				<CoorButton
					iconPosition="start"
					iconName="help"
					intensity="high"
					label="Button"
					color="main"
					size="st3"
				/>
				<CoorButton
					iconPosition="start"
					iconName="help"
					intensity="high"
					label="Button"
					color="main"
					size="st3"
					forceHover
				/>

				<CoorButton
					iconPosition="start"
					iconName="help"
					intensity="high"
					label="Button"
					color="main"
					size="st3"
					active
				/>
				<CoorButton
					iconPosition="start"
					iconName="help"
					intensity="high"
					label="Button"
					color="main"
					size="st3"
					disabled
				/>
			</Box>
			<Box
				gap={'5px'}
				display={'flex'}
				flexDirection={'row'}
			>
				<CoorButton
					intensity="medium"
					label="Button"
					color="main"
					size="st1"
				/>
				<CoorButton
					intensity="medium"
					label="Button"
					color="main"
					size="st1"
					forceHover
				/>

				<CoorButton
					intensity="medium"
					label="Button"
					color="main"
					size="st1"
					active
				/>
				<CoorButton
					intensity="medium"
					label="Button"
					color="main"
					size="st1"
					disabled
				/>
			</Box>
			<Box
				gap={'5px'}
				display={'flex'}
				flexDirection={'row'}
			>
				<CoorButton
					intensity="invert"
					label="Button"
					color="main"
					size="t1"
				/>
				<CoorButton
					intensity="invert"
					label="Button"
					color="main"
					size="t1"
					forceHover
				/>

				<CoorButton
					intensity="invert"
					label="Button"
					color="main"
					size="t1"
					active
				/>
				<CoorButton
					intensity="invert"
					label="Button"
					color="main"
					size="t1"
					disabled
				/>
			</Box>
			<Box
				gap={'5px'}
				display={'flex'}
				flexDirection={'row'}
			>
				<CoorButton
					intensity="low"
					label="Button"
					color="main"
					size="h4"
				/>
				<CoorButton
					intensity="low"
					label="Button"
					color="main"
					size="h4"
					forceHover
				/>

				<CoorButton
					intensity="low"
					label="Button"
					color="main"
					size="h4"
					active
				/>
				<CoorButton
					intensity="low"
					label="Button"
					color="main"
					size="h4"
					disabled
				/>
			</Box>
			<Box
				gap={'5px'}
				display={'flex'}
				flexDirection={'row'}
			>
				<CoorButton
					intensity="lowest"
					label="Button"
					color="main"
					size="h4"
				/>
				<CoorButton
					intensity="lowest"
					label="Button"
					color="main"
					size="h4"
					forceHover
				/>

				<CoorButton
					intensity="lowest"
					label="Button"
					color="main"
					size="h4"
					active
				/>
				<CoorButton
					intensity="lowest"
					label="Button"
					color="main"
					size="h4"
					disabled
				/>
			</Box>
			<Box
				gap={'5px'}
				display={'flex'}
				flexDirection={'row'}
			>
				<CoorButton
					intensity="outline"
					label="Button"
					color="main"
					size="h4"
				/>
				<CoorButton
					intensity="outline"
					label="Button"
					color="main"
					size="h4"
					forceHover
				/>

				<CoorButton
					intensity="outline"
					label="Button"
					color="main"
					size="h4"
					active
				/>
				<CoorButton
					intensity="outline"
					label="Button"
					color="main"
					size="h4"
					disabled
				/>
			</Box>
			<Typography variant="sys.typo.h2">Error Buttons</Typography>
			<Box
				gap={'5px'}
				display={'flex'}
				flexDirection={'row'}
			>
				<CoorButton
					intensity="high"
					label="Button"
					color="error"
					size="h4"
				/>
				<CoorButton
					intensity="high"
					label="Button"
					color="error"
					size="h4"
					forceHover
				/>

				<CoorButton
					intensity="high"
					label="Button"
					color="error"
					size="h4"
					active
				/>
				<CoorButton
					intensity="high"
					label="Button"
					color="error"
					size="h4"
					disabled
				/>
			</Box>
			<Box
				gap={'5px'}
				display={'flex'}
				flexDirection={'row'}
			>
				<CoorButton
					intensity="medium"
					label="Button"
					color="error"
					size="h4"
				/>
				<CoorButton
					intensity="medium"
					label="Button"
					color="error"
					size="h4"
					forceHover
				/>

				<CoorButton
					intensity="medium"
					label="Button"
					color="error"
					size="h4"
					active
				/>
				<CoorButton
					intensity="medium"
					label="Button"
					color="error"
					size="h4"
					disabled
				/>
			</Box>
			<Box
				gap={'5px'}
				display={'flex'}
				flexDirection={'row'}
			>
				<CoorButton
					intensity="low"
					label="Button"
					color="error"
					size="h4"
				/>
				<CoorButton
					intensity="low"
					label="Button"
					color="error"
					size="h4"
					forceHover
				/>

				<CoorButton
					intensity="low"
					label="Button"
					color="error"
					size="h4"
					active
				/>
				<CoorButton
					intensity="low"
					label="Button"
					color="error"
					size="h4"
					disabled
				/>
			</Box>
			<Box
				gap={'5px'}
				display={'flex'}
				flexDirection={'row'}
			>
				<CoorButton
					intensity="lowest"
					label="Button"
					color="error"
					size="h4"
				/>
				<CoorButton
					intensity="lowest"
					label="Button"
					color="error"
					size="h4"
					forceHover
				/>
				<CoorButton
					intensity="lowest"
					label="Button"
					color="error"
					size="h4"
					active
				/>
				<CoorButton
					intensity="lowest"
					label="Button"
					color="error"
					size="h4"
					disabled
				/>
			</Box>
			<Box
				gap={'5px'}
				display={'flex'}
				flexDirection={'row'}
			>
				<CoorButton
					intensity="outline"
					label="Button"
					color="error"
					size="h4"
				/>
				<CoorButton
					intensity="outline"
					label="Button"
					color="error"
					size="h4"
					forceHover
				/>
				<CoorButton
					intensity="outline"
					label="Button"
					color="error"
					size="h4"
					active
				/>
				<CoorButton
					intensity="outline"
					label="Button"
					color="error"
					size="h4"
					disabled
				/>
			</Box>
			<Typography variant="sys.typo.h2">Warning Buttons</Typography>
			<Box
				gap={'5px'}
				display={'flex'}
				flexDirection={'row'}
			>
				<CoorButton
					intensity="high"
					label="Button"
					color="warning"
					size="h4"
				/>
				<CoorButton
					intensity="high"
					label="Button"
					color="warning"
					size="h4"
					forceHover
				/>
				<CoorButton
					intensity="high"
					label="Button"
					color="warning"
					size="h4"
					active
				/>
				<CoorButton
					intensity="high"
					label="Button"
					color="warning"
					size="h4"
					disabled
				/>
			</Box>
			<Box
				gap={'5px'}
				display={'flex'}
				flexDirection={'row'}
			>
				<CoorButton
					intensity="medium"
					label="Button"
					color="warning"
					size="h4"
				/>
				<CoorButton
					intensity="medium"
					label="Button"
					color="warning"
					size="h4"
					forceHover
				/>
				<CoorButton
					intensity="medium"
					label="Button"
					color="warning"
					size="h4"
					active
				/>
				<CoorButton
					intensity="medium"
					label="Button"
					color="warning"
					size="h4"
					disabled
				/>
			</Box>
			<Box
				gap={'5px'}
				display={'flex'}
				flexDirection={'row'}
			>
				<CoorButton
					intensity="low"
					label="Button"
					color="warning"
					size="h4"
				/>
				<CoorButton
					intensity="low"
					label="Button"
					color="warning"
					size="h4"
					forceHover
				/>
				<CoorButton
					intensity="low"
					label="Button"
					color="warning"
					size="h4"
					active
				/>
				<CoorButton
					intensity="low"
					label="Button"
					color="warning"
					size="h4"
					disabled
				/>
			</Box>
			<Box
				gap={'5px'}
				display={'flex'}
				flexDirection={'row'}
			>
				<CoorButton
					intensity="lowest"
					label="Button"
					color="warning"
					size="h4"
				/>
				<CoorButton
					intensity="lowest"
					label="Button"
					color="warning"
					size="h4"
					forceHover
				/>
				<CoorButton
					intensity="lowest"
					label="Button"
					color="warning"
					size="h4"
					active
				/>
				<CoorButton
					intensity="lowest"
					label="Button"
					color="warning"
					size="h4"
					disabled
				/>
			</Box>
			<Box
				gap={'5px'}
				display={'flex'}
				flexDirection={'row'}
			>
				<CoorButton
					intensity="outline"
					label="Button"
					color="warning"
					size="h4"
				/>
				<CoorButton
					intensity="outline"
					label="Button"
					color="warning"
					size="h4"
					forceHover
				/>
				<CoorButton
					intensity="outline"
					label="Button"
					color="warning"
					size="h4"
					active
				/>
				<CoorButton
					intensity="outline"
					label="Button"
					color="warning"
					size="h4"
					disabled
				/>
			</Box>
			<Typography variant="sys.typo.h2">Success Buttons</Typography>
			<Box
				gap={'5px'}
				display={'flex'}
				flexDirection={'row'}
			>
				<CoorButton
					intensity="high"
					label="Button"
					color="success"
					size="t1"
					iconName="help"
					iconPosition="start"
				/>
				<CoorButton
					intensity="high"
					label="Button"
					color="success"
					size="t1"
					forceHover
					iconName="help"
					iconPosition="start"
				/>
				<CoorButton
					intensity="high"
					label="Button"
					color="success"
					size="t1"
					active
					iconName="help"
					iconPosition="start"
				/>
				<CoorButton
					intensity="high"
					label="Button"
					color="success"
					size="t1"
					disabled
					iconName="help"
					iconPosition="start"
				/>
			</Box>
			<Box
				gap={'5px'}
				display={'flex'}
				flexDirection={'row'}
			>
				<CoorButton
					intensity="medium"
					label="Button"
					color="success"
					size="st1"
					iconName="help"
					iconPosition="start"
				/>
				<CoorButton
					intensity="medium"
					label="Button"
					color="success"
					size="st1"
					forceHover
					iconName="help"
					iconPosition="start"
				/>
				<CoorButton
					intensity="medium"
					label="Button"
					color="success"
					size="st1"
					active
					iconName="help"
					iconPosition="start"
				/>
				<CoorButton
					intensity="medium"
					label="Button"
					color="success"
					size="st1"
					disabled
					iconName="help"
					iconPosition="start"
				/>
			</Box>
			<Box
				gap={'5px'}
				display={'flex'}
				flexDirection={'row'}
			>
				<CoorButton
					intensity="low"
					label="Button"
					color="success"
					size="h4"
					iconName="help"
					iconPosition="start"
				/>
				<CoorButton
					intensity="low"
					label="Button"
					color="success"
					size="h4"
					forceHover
					iconName="help"
					iconPosition="start"
				/>
				<CoorButton
					intensity="low"
					label="Button"
					color="success"
					size="h4"
					active
					iconName="help"
					iconPosition="start"
				/>
				<CoorButton
					intensity="low"
					label="Button"
					color="success"
					size="h4"
					disabled
					iconName="help"
					iconPosition="start"
				/>
			</Box>
			<Box
				gap={'5px'}
				display={'flex'}
				flexDirection={'row'}
			>
				<CoorButton
					intensity="lowest"
					label="Button"
					color="success"
					size="h4"
				/>
				<CoorButton
					intensity="lowest"
					label="Button"
					color="success"
					size="h4"
					forceHover
				/>
				<CoorButton
					intensity="lowest"
					label="Button"
					color="success"
					size="h4"
					active
				/>
				<CoorButton
					intensity="lowest"
					label="Button"
					color="success"
					size="h4"
					disabled
				/>
			</Box>
			<Box
				gap={'5px'}
				display={'flex'}
				flexDirection={'row'}
			>
				<CoorButton
					intensity="outline"
					label="Button"
					color="success"
					size="h4"
				/>
				<CoorButton
					intensity="outline"
					label="Button"
					color="success"
					size="h4"
					forceHover
				/>
				<CoorButton
					intensity="outline"
					label="Button"
					color="success"
					size="h4"
					active
				/>
				<CoorButton
					intensity="outline"
					label="Button"
					color="success"
					size="h4"
					disabled
				/>
			</Box>
		</Box>
	)
}

export default CoorButtons
