import { Box, Typography } from '@mui/material'
import { CoorButton } from '../button'

export default function ButtonsExamples() {
	return (
		<Box
			sx={{ padding: '10px' }}
			gap={'5px'}
			display={'flex'}
			flexDirection={'column'}
		>
			<Typography variant="sys.typo.h2">Custom Buttons</Typography>
			<Box
				gap={'5px'}
				display={'flex'}
				flexDirection={'row'}
			>
				<CoorButton
					intensity="high"
					label="Button"
					color="custom"
					customColor="purple"
					size="md"
					iconName="help"
					iconPosition="start"
				/>
				<CoorButton
					intensity="high"
					label="Button"
					color="custom"
					customColor="purple"
					size="md"
					iconName="help"
					iconPosition="end"
					forceHover
				/>
				<CoorButton
					intensity="high"
					label="Button"
					color="custom"
					customColor="purple"
					size="xl"
					forceHover
					iconName="help"
					iconPosition="end"
				/>

				<CoorButton
					intensity="high"
					label="Button"
					color="custom"
					customColor="purple"
					size="xl"
					active
				/>
				<CoorButton
					intensity="high"
					label="Button"
					color="custom"
					customColor="purple"
					size="xl"
					disabled
				/>
			</Box>
			<Box
				gap={'5px'}
				display={'flex'}
				flexDirection={'row'}
			>
				<CoorButton
					intensity="medium"
					label="Button"
					color="custom"
					customColor="purple"
					size="xl"
				/>
				<CoorButton
					intensity="medium"
					label="Button"
					color="custom"
					customColor="purple"
					size="xl"
					forceHover
				/>

				<CoorButton
					intensity="medium"
					label="Button"
					color="custom"
					customColor="purple"
					size="xl"
					active
				/>
				<CoorButton
					intensity="medium"
					label="Button"
					color="custom"
					customColor="purple"
					size="xl"
					disabled
				/>
			</Box>
			<Box
				gap={'5px'}
				display={'flex'}
				flexDirection={'row'}
			>
				<CoorButton
					intensity="invert"
					label="Button"
					color="main"
					size="xl"
					iconName="help"
					iconPosition="start"
				/>
				<CoorButton
					intensity="invert"
					label="Button"
					color="main"
					size="xl"
					forceHover
				/>

				<CoorButton
					intensity="invert"
					label="Button"
					color="main"
					size="xl"
					active
				/>
				<CoorButton
					intensity="invert"
					label="Button"
					color="main"
					size="xl"
					disabled
				/>
			</Box>
			<Box
				gap={'5px'}
				display={'flex'}
				flexDirection={'row'}
			>
				<CoorButton
					intensity="low"
					label="Button"
					color="main"
					size="xl"
				/>
				<CoorButton
					intensity="low"
					label="Button"
					color="main"
					size="xl"
					forceHover
				/>

				<CoorButton
					intensity="low"
					label="Button"
					color="main"
					size="xl"
					active
				/>
				<CoorButton
					intensity="low"
					label="Button"
					color="main"
					size="xl"
					disabled
				/>
			</Box>
			<Box
				gap={'5px'}
				display={'flex'}
				flexDirection={'row'}
			>
				<CoorButton
					intensity="lowest"
					label="Button"
					color="main"
					size="xl"
				/>
				<CoorButton
					intensity="lowest"
					label="Button"
					color="main"
					size="xl"
					forceHover
				/>

				<CoorButton
					intensity="lowest"
					label="Button"
					color="main"
					size="xl"
					active
				/>
				<CoorButton
					intensity="lowest"
					label="Button"
					color="main"
					size="xl"
					disabled
				/>
			</Box>
			<Box
				gap={'5px'}
				display={'flex'}
				flexDirection={'row'}
			>
				<CoorButton
					intensity="outline"
					label="Button"
					color="main"
					size="xl"
				/>
				<CoorButton
					intensity="outline"
					label="Button"
					color="main"
					size="xl"
					forceHover
				/>

				<CoorButton
					intensity="outline"
					label="Button"
					color="main"
					size="xl"
					active
				/>
				<CoorButton
					intensity="outline"
					label="Button"
					color="main"
					size="xl"
					disabled
				/>
			</Box>
			<Typography variant="sys.typo.h2">Main Buttons</Typography>
			<Box
				gap={'5px'}
				display={'flex'}
				flexDirection={'row'}
			>
				<CoorButton
					iconPosition="start"
					iconName="help"
					intensity="high"
					label="Button"
					color="main"
					size="xs"
				/>
				<CoorButton
					iconPosition="start"
					iconName="help"
					intensity="high"
					label="Button"
					color="main"
					size="xs"
					forceHover
				/>

				<CoorButton
					iconPosition="start"
					iconName="help"
					intensity="high"
					label="Button"
					color="main"
					size="xs"
					active
				/>
				<CoorButton
					iconPosition="start"
					iconName="help"
					intensity="high"
					label="Button"
					color="main"
					size="xs"
					disabled
				/>
			</Box>
			<Box
				gap={'5px'}
				display={'flex'}
				flexDirection={'row'}
			>
				<CoorButton
					intensity="medium"
					label="Button"
					color="main"
					size="md"
				/>
				<CoorButton
					intensity="medium"
					label="Button"
					color="main"
					size="md"
					forceHover
				/>

				<CoorButton
					intensity="medium"
					label="Button"
					color="main"
					size="md"
					active
				/>
				<CoorButton
					intensity="medium"
					label="Button"
					color="main"
					size="md"
					disabled
				/>
			</Box>
			<Box
				gap={'5px'}
				display={'flex'}
				flexDirection={'row'}
			>
				<CoorButton
					intensity="invert"
					label="Button"
					color="main"
					size="md"
				/>
				<CoorButton
					intensity="invert"
					label="Button"
					color="main"
					size="md"
					forceHover
				/>

				<CoorButton
					intensity="invert"
					label="Button"
					color="main"
					size="md"
					active
				/>
				<CoorButton
					intensity="invert"
					label="Button"
					color="main"
					size="md"
					disabled
				/>
			</Box>
			<Box
				gap={'5px'}
				display={'flex'}
				flexDirection={'row'}
			>
				<CoorButton
					intensity="low"
					label="Button"
					color="main"
					size="xl"
				/>
				<CoorButton
					intensity="low"
					label="Button"
					color="main"
					size="xl"
					forceHover
				/>

				<CoorButton
					intensity="low"
					label="Button"
					color="main"
					size="xl"
					active
				/>
				<CoorButton
					intensity="low"
					label="Button"
					color="main"
					size="xl"
					disabled
				/>
			</Box>
			<Box
				gap={'5px'}
				display={'flex'}
				flexDirection={'row'}
			>
				<CoorButton
					intensity="lowest"
					label="Button"
					color="main"
					size="xl"
				/>
				<CoorButton
					intensity="lowest"
					label="Button"
					color="main"
					size="xl"
					forceHover
				/>

				<CoorButton
					intensity="lowest"
					label="Button"
					color="main"
					size="xl"
					active
				/>
				<CoorButton
					intensity="lowest"
					label="Button"
					color="main"
					size="xl"
					disabled
				/>
			</Box>
			<Box
				gap={'5px'}
				display={'flex'}
				flexDirection={'row'}
			>
				<CoorButton
					intensity="outline"
					label="Button"
					color="main"
					size="xl"
				/>
				<CoorButton
					intensity="outline"
					label="Button"
					color="main"
					size="xl"
					forceHover
				/>

				<CoorButton
					intensity="outline"
					label="Button"
					color="main"
					size="xl"
					active
				/>
				<CoorButton
					intensity="outline"
					label="Button"
					color="main"
					size="xl"
					disabled
				/>
			</Box>
			<Typography variant="sys.typo.h2">Error Buttons</Typography>
			<Box
				gap={'5px'}
				display={'flex'}
				flexDirection={'row'}
			>
				<CoorButton
					intensity="high"
					label="Button"
					color="error"
					size="xl"
				/>
				<CoorButton
					intensity="high"
					label="Button"
					color="error"
					size="xl"
					forceHover
				/>

				<CoorButton
					intensity="high"
					label="Button"
					color="error"
					size="xl"
					active
				/>
				<CoorButton
					intensity="high"
					label="Button"
					color="error"
					size="xl"
					disabled
				/>
			</Box>
			<Box
				gap={'5px'}
				display={'flex'}
				flexDirection={'row'}
			>
				<CoorButton
					intensity="medium"
					label="Button"
					color="error"
					size="xl"
				/>
				<CoorButton
					intensity="medium"
					label="Button"
					color="error"
					size="xl"
					forceHover
				/>

				<CoorButton
					intensity="medium"
					label="Button"
					color="error"
					size="xl"
					active
				/>
				<CoorButton
					intensity="medium"
					label="Button"
					color="error"
					size="xl"
					disabled
				/>
			</Box>
			<Box
				gap={'5px'}
				display={'flex'}
				flexDirection={'row'}
			>
				<CoorButton
					intensity="low"
					label="Button"
					color="error"
					size="xl"
				/>
				<CoorButton
					intensity="low"
					label="Button"
					color="error"
					size="xl"
					forceHover
				/>

				<CoorButton
					intensity="low"
					label="Button"
					color="error"
					size="xl"
					active
				/>
				<CoorButton
					intensity="low"
					label="Button"
					color="error"
					size="xl"
					disabled
				/>
			</Box>
			<Box
				gap={'5px'}
				display={'flex'}
				flexDirection={'row'}
			>
				<CoorButton
					intensity="lowest"
					label="Button"
					color="error"
					size="xl"
				/>
				<CoorButton
					intensity="lowest"
					label="Button"
					color="error"
					size="xl"
					forceHover
				/>
				<CoorButton
					intensity="lowest"
					label="Button"
					color="error"
					size="xl"
					active
				/>
				<CoorButton
					intensity="lowest"
					label="Button"
					color="error"
					size="xl"
					disabled
				/>
			</Box>
			<Box
				gap={'5px'}
				display={'flex'}
				flexDirection={'row'}
			>
				<CoorButton
					intensity="outline"
					label="Button"
					color="error"
					size="xl"
				/>
				<CoorButton
					intensity="outline"
					label="Button"
					color="error"
					size="xl"
					forceHover
				/>
				<CoorButton
					intensity="outline"
					label="Button"
					color="error"
					size="xl"
					active
				/>
				<CoorButton
					intensity="outline"
					label="Button"
					color="error"
					size="xl"
					disabled
				/>
			</Box>
			<Typography variant="sys.typo.h2">Warning Buttons</Typography>
			<Box
				gap={'5px'}
				display={'flex'}
				flexDirection={'row'}
			>
				<CoorButton
					intensity="high"
					label="Button"
					color="warning"
					size="xl"
				/>
				<CoorButton
					intensity="high"
					label="Button"
					color="warning"
					size="xl"
					forceHover
				/>
				<CoorButton
					intensity="high"
					label="Button"
					color="warning"
					size="xl"
					active
				/>
				<CoorButton
					intensity="high"
					label="Button"
					color="warning"
					size="xl"
					disabled
				/>
			</Box>
			<Box
				gap={'5px'}
				display={'flex'}
				flexDirection={'row'}
			>
				<CoorButton
					intensity="medium"
					label="Button"
					color="warning"
					size="xl"
				/>
				<CoorButton
					intensity="medium"
					label="Button"
					color="warning"
					size="xl"
					forceHover
				/>
				<CoorButton
					intensity="medium"
					label="Button"
					color="warning"
					size="xl"
					active
				/>
				<CoorButton
					intensity="medium"
					label="Button"
					color="warning"
					size="xl"
					disabled
				/>
			</Box>
			<Box
				gap={'5px'}
				display={'flex'}
				flexDirection={'row'}
			>
				<CoorButton
					intensity="low"
					label="Button"
					color="warning"
					size="xl"
				/>
				<CoorButton
					intensity="low"
					label="Button"
					color="warning"
					size="xl"
					forceHover
				/>
				<CoorButton
					intensity="low"
					label="Button"
					color="warning"
					size="xl"
					active
				/>
				<CoorButton
					intensity="low"
					label="Button"
					color="warning"
					size="xl"
					disabled
				/>
			</Box>
			<Box
				gap={'5px'}
				display={'flex'}
				flexDirection={'row'}
			>
				<CoorButton
					intensity="lowest"
					label="Button"
					color="warning"
					size="xl"
				/>
				<CoorButton
					intensity="lowest"
					label="Button"
					color="warning"
					size="xl"
					forceHover
				/>
				<CoorButton
					intensity="lowest"
					label="Button"
					color="warning"
					size="xl"
					active
				/>
				<CoorButton
					intensity="lowest"
					label="Button"
					color="warning"
					size="xl"
					disabled
				/>
			</Box>
			<Box
				gap={'5px'}
				display={'flex'}
				flexDirection={'row'}
			>
				<CoorButton
					intensity="outline"
					label="Button"
					color="warning"
					size="xl"
				/>
				<CoorButton
					intensity="outline"
					label="Button"
					color="warning"
					size="xl"
					forceHover
				/>
				<CoorButton
					intensity="outline"
					label="Button"
					color="warning"
					size="xl"
					active
				/>
				<CoorButton
					intensity="outline"
					label="Button"
					color="warning"
					size="xl"
					disabled
				/>
			</Box>
			<Typography variant="sys.typo.h2">Success Buttons</Typography>
			<Box
				gap={'5px'}
				display={'flex'}
				flexDirection={'row'}
			>
				<CoorButton
					intensity="high"
					label="Button"
					color="success"
					size="md"
					iconName="help"
					iconPosition="start"
				/>
				<CoorButton
					intensity="high"
					label="Button"
					color="success"
					size="md"
					forceHover
					iconName="help"
					iconPosition="start"
				/>
				<CoorButton
					intensity="high"
					label="Button"
					color="success"
					size="md"
					active
					iconName="help"
					iconPosition="start"
				/>
				<CoorButton
					intensity="high"
					label="Button"
					color="success"
					size="md"
					disabled
					iconName="help"
					iconPosition="start"
				/>
			</Box>
			<Box
				gap={'5px'}
				display={'flex'}
				flexDirection={'row'}
			>
				<CoorButton
					intensity="medium"
					label="Button"
					color="success"
					size="md"
					iconName="help"
					iconPosition="start"
				/>
				<CoorButton
					intensity="medium"
					label="Button"
					color="success"
					size="md"
					forceHover
					iconName="help"
					iconPosition="start"
				/>
				<CoorButton
					intensity="medium"
					label="Button"
					color="success"
					size="md"
					active
					iconName="help"
					iconPosition="start"
				/>
				<CoorButton
					intensity="medium"
					label="Button"
					color="success"
					size="md"
					disabled
					iconName="help"
					iconPosition="start"
				/>
			</Box>
			<Box
				gap={'5px'}
				display={'flex'}
				flexDirection={'row'}
			>
				<CoorButton
					intensity="low"
					label="Button"
					color="success"
					size="xl"
					iconName="help"
					iconPosition="start"
				/>
				<CoorButton
					intensity="low"
					label="Button"
					color="success"
					size="xl"
					forceHover
					iconName="help"
					iconPosition="start"
				/>
				<CoorButton
					intensity="low"
					label="Button"
					color="success"
					size="xl"
					active
					iconName="help"
					iconPosition="start"
				/>
				<CoorButton
					intensity="low"
					label="Button"
					color="success"
					size="xl"
					disabled
					iconName="help"
					iconPosition="start"
				/>
			</Box>
			<Box
				gap={'5px'}
				display={'flex'}
				flexDirection={'row'}
			>
				<CoorButton
					intensity="lowest"
					label="Button"
					color="success"
					size="xl"
				/>
				<CoorButton
					intensity="lowest"
					label="Button"
					color="success"
					size="xl"
					forceHover
				/>
				<CoorButton
					intensity="lowest"
					label="Button"
					color="success"
					size="xl"
					active
				/>
				<CoorButton
					intensity="lowest"
					label="Button"
					color="success"
					size="xl"
					disabled
				/>
			</Box>
			<Box
				gap={'5px'}
				display={'flex'}
				flexDirection={'row'}
			>
				<CoorButton
					intensity="outline"
					label="Button"
					color="success"
					size="xl"
				/>
				<CoorButton
					intensity="outline"
					label="Button"
					color="success"
					size="xl"
					forceHover
				/>
				<CoorButton
					intensity="outline"
					label="Button"
					color="success"
					size="xl"
					active
				/>
				<CoorButton
					intensity="outline"
					label="Button"
					color="success"
					size="xl"
					disabled
				/>
			</Box>
		</Box>
	)
}
