import { Box, Typography } from '@mui/material'
import { CoorIconButton } from '..'

export default function IconButtonsExamples() {
	return (
		<Box
			sx={{ padding: '10px' }}
			gap={'5px'}
			display={'flex'}
			flexDirection={'column'}
		>
			<Typography variant="sys.typo.h2">Main Buttons</Typography>
			<Box
				gap={'5px'}
				display={'flex'}
				flexDirection={'row'}
			>
				<CoorIconButton
					intensity="high"
					color="custom"
					customColor="magenta"
					size="xl"
					iconName="help"
				/>
				<CoorIconButton
					intensity="high"
					color="custom"
					customColor="magenta"
					size="xl"
					iconName="help"
					forceHover
				/>

				<CoorIconButton
					intensity="high"
					color="custom"
					customColor="magenta"
					size="xl"
					iconName="help"
					active
				/>
				<CoorIconButton
					intensity="high"
					color="custom"
					customColor="magenta"
					size="xl"
					iconName="help"
					disabled
				/>
			</Box>
			<Box
				gap={'5px'}
				display={'flex'}
				flexDirection={'row'}
			>
				<CoorIconButton
					intensity="medium"
					color="main"
					size="xl"
					iconName="help"
				/>
				<CoorIconButton
					intensity="medium"
					color="main"
					size="xl"
					iconName="help"
					forceHover
				/>

				<CoorIconButton
					intensity="medium"
					color="main"
					size="xl"
					iconName="help"
					active
				/>
				<CoorIconButton
					intensity="medium"
					color="main"
					size="xl"
					iconName="help"
					disabled
				/>
			</Box>
			<Box
				gap={'5px'}
				display={'flex'}
				flexDirection={'row'}
			>
				<CoorIconButton
					intensity="low"
					color="main"
					size="xl"
					iconName="help"
				/>
				<CoorIconButton
					intensity="low"
					color="main"
					size="xl"
					iconName="help"
					forceHover
				/>

				<CoorIconButton
					intensity="low"
					color="main"
					size="xl"
					iconName="help"
					active
				/>
				<CoorIconButton
					intensity="low"
					color="main"
					size="xl"
					iconName="help"
					disabled
				/>
			</Box>
			<Box
				gap={'5px'}
				display={'flex'}
				flexDirection={'row'}
			>
				<CoorIconButton
					intensity="lowest"
					color="main"
					size="xl"
					iconName="help"
				/>
				<CoorIconButton
					intensity="lowest"
					color="main"
					size="xl"
					iconName="help"
					forceHover
				/>

				<CoorIconButton
					intensity="lowest"
					color="main"
					size="xl"
					iconName="help"
					active
				/>
				<CoorIconButton
					intensity="lowest"
					color="main"
					size="xl"
					iconName="help"
					disabled
				/>
			</Box>
			<Box
				gap={'5px'}
				display={'flex'}
				flexDirection={'row'}
			>
				<CoorIconButton
					intensity="outline"
					color="main"
					size="xl"
					iconName="help"
				/>
				<CoorIconButton
					intensity="outline"
					color="main"
					size="xl"
					iconName="help"
					forceHover
				/>

				<CoorIconButton
					intensity="outline"
					color="main"
					size="xl"
					iconName="help"
					active
				/>
				<CoorIconButton
					intensity="outline"
					color="main"
					size="xl"
					iconName="help"
					disabled
				/>
			</Box>
			<Box
				gap={'5px'}
				display={'flex'}
				flexDirection={'row'}
			>
				<CoorIconButton
					intensity="invert"
					color="main"
					size="xl"
					iconName="help"
				/>
				<CoorIconButton
					intensity="invert"
					color="main"
					size="xl"
					iconName="help"
					forceHover
				/>

				<CoorIconButton
					intensity="invert"
					color="main"
					size="xl"
					iconName="help"
					active
				/>
				<CoorIconButton
					intensity="invert"
					color="main"
					size="xl"
					iconName="help"
					disabled
				/>
			</Box>
			<Box
				gap={'5px'}
				display={'flex'}
				flexDirection={'row'}
			>
				<CoorIconButton
					intensity="high"
					color="main"
					size="lg"
					iconName="help"
				/>
				<CoorIconButton
					intensity="high"
					color="main"
					size="lg"
					iconName="help"
					forceHover
				/>

				<CoorIconButton
					intensity="high"
					color="main"
					size="lg"
					iconName="help"
					active
				/>
				<CoorIconButton
					intensity="high"
					color="main"
					size="lg"
					iconName="help"
					disabled
				/>
			</Box>
			<Box
				gap={'5px'}
				display={'flex'}
				flexDirection={'row'}
			>
				<CoorIconButton
					intensity="medium"
					color="main"
					size="lg"
					iconName="help"
				/>
				<CoorIconButton
					intensity="medium"
					color="main"
					size="lg"
					iconName="help"
					forceHover
				/>

				<CoorIconButton
					intensity="medium"
					color="main"
					size="lg"
					iconName="help"
					active
				/>
				<CoorIconButton
					intensity="medium"
					color="main"
					size="lg"
					iconName="help"
					disabled
				/>
			</Box>
			<Box
				gap={'5px'}
				display={'flex'}
				flexDirection={'row'}
			>
				<CoorIconButton
					intensity="low"
					color="main"
					size="lg"
					iconName="help"
				/>
				<CoorIconButton
					intensity="low"
					color="main"
					size="lg"
					iconName="help"
					forceHover
				/>

				<CoorIconButton
					intensity="low"
					color="main"
					size="lg"
					iconName="help"
					active
				/>
				<CoorIconButton
					intensity="low"
					color="main"
					size="lg"
					iconName="help"
					disabled
				/>
			</Box>
			<Box
				gap={'5px'}
				display={'flex'}
				flexDirection={'row'}
			>
				<CoorIconButton
					intensity="lowest"
					color="main"
					size="lg"
					iconName="help"
				/>
				<CoorIconButton
					intensity="lowest"
					color="main"
					size="lg"
					iconName="help"
					forceHover
				/>

				<CoorIconButton
					intensity="lowest"
					color="main"
					size="lg"
					iconName="help"
					active
				/>
				<CoorIconButton
					intensity="lowest"
					color="main"
					size="lg"
					iconName="help"
					disabled
				/>
			</Box>
			<Box
				gap={'5px'}
				display={'flex'}
				flexDirection={'row'}
			>
				<CoorIconButton
					intensity="outline"
					color="main"
					size="lg"
					iconName="help"
				/>
				<CoorIconButton
					intensity="outline"
					color="main"
					size="lg"
					iconName="help"
					forceHover
				/>

				<CoorIconButton
					intensity="outline"
					color="main"
					size="lg"
					iconName="help"
					active
				/>
				<CoorIconButton
					intensity="outline"
					color="main"
					size="lg"
					iconName="help"
					disabled
				/>
			</Box>
			<Box
				gap={'5px'}
				display={'flex'}
				flexDirection={'row'}
			>
				<CoorIconButton
					intensity="invert"
					color="main"
					size="lg"
					iconName="help"
				/>
				<CoorIconButton
					intensity="invert"
					color="main"
					size="lg"
					iconName="help"
					forceHover
				/>

				<CoorIconButton
					intensity="invert"
					color="main"
					size="lg"
					iconName="help"
					active
				/>
				<CoorIconButton
					intensity="invert"
					color="main"
					size="lg"
					iconName="help"
					disabled
				/>
			</Box>
			<Box
				gap={'5px'}
				display={'flex'}
				flexDirection={'row'}
			>
				<CoorIconButton
					intensity="high"
					color="main"
					size="md"
					iconName="help"
				/>
				<CoorIconButton
					intensity="high"
					color="main"
					size="md"
					iconName="help"
					forceHover
				/>

				<CoorIconButton
					intensity="high"
					color="main"
					size="md"
					iconName="help"
					active
				/>
				<CoorIconButton
					intensity="high"
					color="main"
					size="md"
					iconName="help"
					disabled
				/>
			</Box>
			<Box
				gap={'5px'}
				display={'flex'}
				flexDirection={'row'}
			>
				<CoorIconButton
					intensity="medium"
					color="main"
					size="md"
					iconName="help"
				/>
				<CoorIconButton
					intensity="medium"
					color="main"
					size="md"
					iconName="help"
					forceHover
				/>

				<CoorIconButton
					intensity="medium"
					color="main"
					size="md"
					iconName="help"
					active
				/>
				<CoorIconButton
					intensity="medium"
					color="main"
					size="md"
					iconName="help"
					disabled
				/>
			</Box>
			<Box
				gap={'5px'}
				display={'flex'}
				flexDirection={'row'}
			>
				<CoorIconButton
					intensity="low"
					color="main"
					size="md"
					iconName="help"
				/>
				<CoorIconButton
					intensity="low"
					color="main"
					size="md"
					iconName="help"
					forceHover
				/>

				<CoorIconButton
					intensity="low"
					color="main"
					size="md"
					iconName="help"
					active
				/>
				<CoorIconButton
					intensity="low"
					color="main"
					size="md"
					iconName="help"
					disabled
				/>
			</Box>
			<Box
				gap={'5px'}
				display={'flex'}
				flexDirection={'row'}
			>
				<CoorIconButton
					intensity="lowest"
					color="main"
					size="md"
					iconName="help"
				/>
				<CoorIconButton
					intensity="lowest"
					color="main"
					size="md"
					iconName="help"
					forceHover
				/>

				<CoorIconButton
					intensity="lowest"
					color="main"
					size="md"
					iconName="help"
					active
				/>
				<CoorIconButton
					intensity="lowest"
					color="main"
					size="md"
					iconName="help"
					disabled
				/>
			</Box>
			<Box
				gap={'5px'}
				display={'flex'}
				flexDirection={'row'}
			>
				<CoorIconButton
					intensity="outline"
					color="main"
					size="md"
					iconName="help"
				/>
				<CoorIconButton
					intensity="outline"
					color="main"
					size="md"
					iconName="help"
					forceHover
				/>

				<CoorIconButton
					intensity="outline"
					color="main"
					size="md"
					iconName="help"
					active
				/>
				<CoorIconButton
					intensity="outline"
					color="main"
					size="md"
					iconName="help"
					disabled
				/>
			</Box>
			<Box
				gap={'5px'}
				display={'flex'}
				flexDirection={'row'}
			>
				<CoorIconButton
					intensity="invert"
					color="main"
					size="md"
					iconName="help"
				/>
				<CoorIconButton
					intensity="invert"
					color="main"
					size="md"
					iconName="help"
					forceHover
				/>

				<CoorIconButton
					intensity="invert"
					color="main"
					size="md"
					iconName="help"
					active
				/>
				<CoorIconButton
					intensity="invert"
					color="main"
					size="md"
					iconName="help"
					disabled
				/>
			</Box>
			<Typography variant="sys.typo.h2">Success Buttons</Typography>
			<Box
				gap={'5px'}
				display={'flex'}
				flexDirection={'row'}
			>
				<CoorIconButton
					intensity="high"
					color="success"
					size="xl"
					iconName="help"
				/>
				<CoorIconButton
					intensity="high"
					color="success"
					size="xl"
					iconName="help"
					forceHover
				/>

				<CoorIconButton
					intensity="high"
					color="success"
					size="xl"
					iconName="help"
					active
				/>
				<CoorIconButton
					intensity="high"
					color="success"
					size="xl"
					iconName="help"
					disabled
				/>
			</Box>
			<Box
				gap={'5px'}
				display={'flex'}
				flexDirection={'row'}
			>
				<CoorIconButton
					intensity="medium"
					color="success"
					size="xl"
					iconName="help"
				/>
				<CoorIconButton
					intensity="medium"
					color="success"
					size="xl"
					iconName="help"
					forceHover
				/>

				<CoorIconButton
					intensity="medium"
					color="success"
					size="xl"
					iconName="help"
					active
				/>
				<CoorIconButton
					intensity="medium"
					color="success"
					size="xl"
					iconName="help"
					disabled
				/>
			</Box>
			<Box
				gap={'5px'}
				display={'flex'}
				flexDirection={'row'}
			>
				<CoorIconButton
					intensity="low"
					color="success"
					size="xl"
					iconName="help"
				/>
				<CoorIconButton
					intensity="low"
					color="success"
					size="xl"
					iconName="help"
					forceHover
				/>

				<CoorIconButton
					intensity="low"
					color="success"
					size="xl"
					iconName="help"
					active
				/>
				<CoorIconButton
					intensity="low"
					color="success"
					size="xl"
					iconName="help"
					disabled
				/>
			</Box>
			<Box
				gap={'5px'}
				display={'flex'}
				flexDirection={'row'}
			>
				<CoorIconButton
					intensity="lowest"
					color="success"
					size="xl"
					iconName="help"
				/>
				<CoorIconButton
					intensity="lowest"
					color="success"
					size="xl"
					iconName="help"
					forceHover
				/>

				<CoorIconButton
					intensity="lowest"
					color="success"
					size="xl"
					iconName="help"
					active
				/>
				<CoorIconButton
					intensity="lowest"
					color="success"
					size="xl"
					iconName="help"
					disabled
				/>
			</Box>
			<Box
				gap={'5px'}
				display={'flex'}
				flexDirection={'row'}
			>
				<CoorIconButton
					intensity="outline"
					color="success"
					size="xl"
					iconName="help"
				/>
				<CoorIconButton
					intensity="outline"
					color="success"
					size="xl"
					iconName="help"
					forceHover
				/>

				<CoorIconButton
					intensity="outline"
					color="success"
					size="xl"
					iconName="help"
					active
				/>
				<CoorIconButton
					intensity="outline"
					color="success"
					size="xl"
					iconName="help"
					disabled
				/>
			</Box>

			<Box
				gap={'5px'}
				display={'flex'}
				flexDirection={'row'}
			>
				<CoorIconButton
					intensity="high"
					color="success"
					size="lg"
					iconName="help"
				/>
				<CoorIconButton
					intensity="high"
					color="success"
					size="lg"
					iconName="help"
					forceHover
				/>

				<CoorIconButton
					intensity="high"
					color="success"
					size="lg"
					iconName="help"
					active
				/>
				<CoorIconButton
					intensity="high"
					color="success"
					size="lg"
					iconName="help"
					disabled
				/>
			</Box>
			<Box
				gap={'5px'}
				display={'flex'}
				flexDirection={'row'}
			>
				<CoorIconButton
					intensity="medium"
					color="success"
					size="lg"
					iconName="help"
				/>
				<CoorIconButton
					intensity="medium"
					color="success"
					size="lg"
					iconName="help"
					forceHover
				/>

				<CoorIconButton
					intensity="medium"
					color="success"
					size="lg"
					iconName="help"
					active
				/>
				<CoorIconButton
					intensity="medium"
					color="success"
					size="lg"
					iconName="help"
					disabled
				/>
			</Box>
			<Box
				gap={'5px'}
				display={'flex'}
				flexDirection={'row'}
			>
				<CoorIconButton
					intensity="low"
					color="success"
					size="lg"
					iconName="help"
				/>
				<CoorIconButton
					intensity="low"
					color="success"
					size="lg"
					iconName="help"
					forceHover
				/>

				<CoorIconButton
					intensity="low"
					color="success"
					size="lg"
					iconName="help"
					active
				/>
				<CoorIconButton
					intensity="low"
					color="success"
					size="lg"
					iconName="help"
					disabled
				/>
			</Box>
			<Box
				gap={'5px'}
				display={'flex'}
				flexDirection={'row'}
			>
				<CoorIconButton
					intensity="lowest"
					color="success"
					size="lg"
					iconName="help"
				/>
				<CoorIconButton
					intensity="lowest"
					color="success"
					size="lg"
					iconName="help"
					forceHover
				/>

				<CoorIconButton
					intensity="lowest"
					color="success"
					size="lg"
					iconName="help"
					active
				/>
				<CoorIconButton
					intensity="lowest"
					color="success"
					size="lg"
					iconName="help"
					disabled
				/>
			</Box>
			<Box
				gap={'5px'}
				display={'flex'}
				flexDirection={'row'}
			>
				<CoorIconButton
					intensity="outline"
					color="success"
					size="lg"
					iconName="help"
				/>
				<CoorIconButton
					intensity="outline"
					color="success"
					size="lg"
					iconName="help"
					forceHover
				/>

				<CoorIconButton
					intensity="outline"
					color="success"
					size="lg"
					iconName="help"
					active
				/>
				<CoorIconButton
					intensity="outline"
					color="success"
					size="lg"
					iconName="help"
					disabled
				/>
			</Box>

			<Box
				gap={'5px'}
				display={'flex'}
				flexDirection={'row'}
			>
				<CoorIconButton
					intensity="high"
					color="success"
					size="md"
					iconName="help"
				/>
				<CoorIconButton
					intensity="high"
					color="success"
					size="md"
					iconName="help"
					forceHover
				/>

				<CoorIconButton
					intensity="high"
					color="success"
					size="md"
					iconName="help"
					active
				/>
				<CoorIconButton
					intensity="high"
					color="success"
					size="md"
					iconName="help"
					disabled
				/>
			</Box>
			<Box
				gap={'5px'}
				display={'flex'}
				flexDirection={'row'}
			>
				<CoorIconButton
					intensity="medium"
					color="success"
					size="md"
					iconName="help"
				/>
				<CoorIconButton
					intensity="medium"
					color="success"
					size="md"
					iconName="help"
					forceHover
				/>

				<CoorIconButton
					intensity="medium"
					color="success"
					size="md"
					iconName="help"
					active
				/>
				<CoorIconButton
					intensity="medium"
					color="success"
					size="md"
					iconName="help"
					disabled
				/>
			</Box>
			<Box
				gap={'5px'}
				display={'flex'}
				flexDirection={'row'}
			>
				<CoorIconButton
					intensity="low"
					color="success"
					size="md"
					iconName="help"
				/>
				<CoorIconButton
					intensity="low"
					color="success"
					size="md"
					iconName="help"
					forceHover
				/>

				<CoorIconButton
					intensity="low"
					color="success"
					size="md"
					iconName="help"
					active
				/>
				<CoorIconButton
					intensity="low"
					color="success"
					size="md"
					iconName="help"
					disabled
				/>
			</Box>
			<Box
				gap={'5px'}
				display={'flex'}
				flexDirection={'row'}
			>
				<CoorIconButton
					intensity="lowest"
					color="success"
					size="md"
					iconName="help"
				/>
				<CoorIconButton
					intensity="lowest"
					color="success"
					size="md"
					iconName="help"
					forceHover
				/>

				<CoorIconButton
					intensity="lowest"
					color="success"
					size="md"
					iconName="help"
					active
				/>
				<CoorIconButton
					intensity="lowest"
					color="success"
					size="md"
					iconName="help"
					disabled
				/>
			</Box>
			<Box
				gap={'5px'}
				display={'flex'}
				flexDirection={'row'}
			>
				<CoorIconButton
					intensity="outline"
					color="success"
					size="md"
					iconName="help"
				/>
				<CoorIconButton
					intensity="outline"
					color="success"
					size="md"
					iconName="help"
					forceHover
				/>

				<CoorIconButton
					intensity="outline"
					color="success"
					size="md"
					iconName="help"
					active
				/>
				<CoorIconButton
					intensity="outline"
					color="success"
					size="md"
					iconName="help"
					disabled
				/>
			</Box>
			<Typography variant="sys.typo.h2">Warning Buttons</Typography>
			<Box
				gap={'5px'}
				display={'flex'}
				flexDirection={'row'}
			>
				<CoorIconButton
					intensity="high"
					color="warning"
					size="xl"
					iconName="help"
				/>
				<CoorIconButton
					intensity="high"
					color="warning"
					size="xl"
					iconName="help"
					forceHover
				/>

				<CoorIconButton
					intensity="high"
					color="warning"
					size="xl"
					iconName="help"
					active
				/>
				<CoorIconButton
					intensity="high"
					color="warning"
					size="xl"
					iconName="help"
					disabled
				/>
			</Box>
			<Box
				gap={'5px'}
				display={'flex'}
				flexDirection={'row'}
			>
				<CoorIconButton
					intensity="medium"
					color="warning"
					size="xl"
					iconName="help"
				/>
				<CoorIconButton
					intensity="medium"
					color="warning"
					size="xl"
					iconName="help"
					forceHover
				/>

				<CoorIconButton
					intensity="medium"
					color="warning"
					size="xl"
					iconName="help"
					active
				/>
				<CoorIconButton
					intensity="medium"
					color="warning"
					size="xl"
					iconName="help"
					disabled
				/>
			</Box>
			<Box
				gap={'5px'}
				display={'flex'}
				flexDirection={'row'}
			>
				<CoorIconButton
					intensity="low"
					color="warning"
					size="xl"
					iconName="help"
				/>
				<CoorIconButton
					intensity="low"
					color="warning"
					size="xl"
					iconName="help"
					forceHover
				/>

				<CoorIconButton
					intensity="low"
					color="warning"
					size="xl"
					iconName="help"
					active
				/>
				<CoorIconButton
					intensity="low"
					color="warning"
					size="xl"
					iconName="help"
					disabled
				/>
			</Box>
			<Box
				gap={'5px'}
				display={'flex'}
				flexDirection={'row'}
			>
				<CoorIconButton
					intensity="lowest"
					color="warning"
					size="xl"
					iconName="help"
				/>
				<CoorIconButton
					intensity="lowest"
					color="warning"
					size="xl"
					iconName="help"
					forceHover
				/>

				<CoorIconButton
					intensity="lowest"
					color="warning"
					size="xl"
					iconName="help"
					active
				/>
				<CoorIconButton
					intensity="lowest"
					color="warning"
					size="xl"
					iconName="help"
					disabled
				/>
			</Box>
			<Box
				gap={'5px'}
				display={'flex'}
				flexDirection={'row'}
			>
				<CoorIconButton
					intensity="outline"
					color="warning"
					size="xl"
					iconName="help"
				/>
				<CoorIconButton
					intensity="outline"
					color="warning"
					size="xl"
					iconName="help"
					forceHover
				/>

				<CoorIconButton
					intensity="outline"
					color="warning"
					size="xl"
					iconName="help"
					active
				/>
				<CoorIconButton
					intensity="outline"
					color="warning"
					size="xl"
					iconName="help"
					disabled
				/>
			</Box>

			<Box
				gap={'5px'}
				display={'flex'}
				flexDirection={'row'}
			>
				<CoorIconButton
					intensity="high"
					color="warning"
					size="lg"
					iconName="help"
				/>
				<CoorIconButton
					intensity="high"
					color="warning"
					size="lg"
					iconName="help"
					forceHover
				/>

				<CoorIconButton
					intensity="high"
					color="warning"
					size="lg"
					iconName="help"
					active
				/>
				<CoorIconButton
					intensity="high"
					color="warning"
					size="lg"
					iconName="help"
					disabled
				/>
			</Box>
			<Box
				gap={'5px'}
				display={'flex'}
				flexDirection={'row'}
			>
				<CoorIconButton
					intensity="medium"
					color="warning"
					size="lg"
					iconName="help"
				/>
				<CoorIconButton
					intensity="medium"
					color="warning"
					size="lg"
					iconName="help"
					forceHover
				/>

				<CoorIconButton
					intensity="medium"
					color="warning"
					size="lg"
					iconName="help"
					active
				/>
				<CoorIconButton
					intensity="medium"
					color="warning"
					size="lg"
					iconName="help"
					disabled
				/>
			</Box>
			<Box
				gap={'5px'}
				display={'flex'}
				flexDirection={'row'}
			>
				<CoorIconButton
					intensity="low"
					color="warning"
					size="lg"
					iconName="help"
				/>
				<CoorIconButton
					intensity="low"
					color="warning"
					size="lg"
					iconName="help"
					forceHover
				/>

				<CoorIconButton
					intensity="low"
					color="warning"
					size="lg"
					iconName="help"
					active
				/>
				<CoorIconButton
					intensity="low"
					color="warning"
					size="lg"
					iconName="help"
					disabled
				/>
			</Box>
			<Box
				gap={'5px'}
				display={'flex'}
				flexDirection={'row'}
			>
				<CoorIconButton
					intensity="lowest"
					color="warning"
					size="lg"
					iconName="help"
				/>
				<CoorIconButton
					intensity="lowest"
					color="warning"
					size="lg"
					iconName="help"
					forceHover
				/>

				<CoorIconButton
					intensity="lowest"
					color="warning"
					size="lg"
					iconName="help"
					active
				/>
				<CoorIconButton
					intensity="lowest"
					color="warning"
					size="lg"
					iconName="help"
					disabled
				/>
			</Box>
			<Box
				gap={'5px'}
				display={'flex'}
				flexDirection={'row'}
			>
				<CoorIconButton
					intensity="outline"
					color="warning"
					size="lg"
					iconName="help"
				/>
				<CoorIconButton
					intensity="outline"
					color="warning"
					size="lg"
					iconName="help"
					forceHover
				/>

				<CoorIconButton
					intensity="outline"
					color="warning"
					size="lg"
					iconName="help"
					active
				/>
				<CoorIconButton
					intensity="outline"
					color="warning"
					size="lg"
					iconName="help"
					disabled
				/>
			</Box>

			<Box
				gap={'5px'}
				display={'flex'}
				flexDirection={'row'}
			>
				<CoorIconButton
					intensity="high"
					color="warning"
					size="md"
					iconName="help"
				/>
				<CoorIconButton
					intensity="high"
					color="warning"
					size="md"
					iconName="help"
					forceHover
				/>

				<CoorIconButton
					intensity="high"
					color="warning"
					size="md"
					iconName="help"
					active
				/>
				<CoorIconButton
					intensity="high"
					color="warning"
					size="md"
					iconName="help"
					disabled
				/>
			</Box>
			<Box
				gap={'5px'}
				display={'flex'}
				flexDirection={'row'}
			>
				<CoorIconButton
					intensity="medium"
					color="warning"
					size="md"
					iconName="help"
				/>
				<CoorIconButton
					intensity="medium"
					color="warning"
					size="md"
					iconName="help"
					forceHover
				/>

				<CoorIconButton
					intensity="medium"
					color="warning"
					size="md"
					iconName="help"
					active
				/>
				<CoorIconButton
					intensity="medium"
					color="warning"
					size="md"
					iconName="help"
					disabled
				/>
			</Box>
			<Box
				gap={'5px'}
				display={'flex'}
				flexDirection={'row'}
			>
				<CoorIconButton
					intensity="low"
					color="warning"
					size="md"
					iconName="help"
				/>
				<CoorIconButton
					intensity="low"
					color="warning"
					size="md"
					iconName="help"
					forceHover
				/>

				<CoorIconButton
					intensity="low"
					color="warning"
					size="md"
					iconName="help"
					active
				/>
				<CoorIconButton
					intensity="low"
					color="warning"
					size="md"
					iconName="help"
					disabled
				/>
			</Box>
			<Box
				gap={'5px'}
				display={'flex'}
				flexDirection={'row'}
			>
				<CoorIconButton
					intensity="lowest"
					color="warning"
					size="md"
					iconName="help"
				/>
				<CoorIconButton
					intensity="lowest"
					color="warning"
					size="md"
					iconName="help"
					forceHover
				/>

				<CoorIconButton
					intensity="lowest"
					color="warning"
					size="md"
					iconName="help"
					active
				/>
				<CoorIconButton
					intensity="lowest"
					color="warning"
					size="md"
					iconName="help"
					disabled
				/>
			</Box>
			<Box
				gap={'5px'}
				display={'flex'}
				flexDirection={'row'}
			>
				<CoorIconButton
					intensity="outline"
					color="warning"
					size="md"
					iconName="help"
				/>
				<CoorIconButton
					intensity="outline"
					color="warning"
					size="md"
					iconName="help"
					forceHover
				/>

				<CoorIconButton
					intensity="outline"
					color="warning"
					size="md"
					iconName="help"
					active
				/>
				<CoorIconButton
					intensity="outline"
					color="warning"
					size="md"
					iconName="help"
					disabled
				/>
			</Box>
		</Box>
	)
}
