// app/components/MiComponente.tsx
'use client'

import { Box } from '@mui/material'
import { CoorIconChip, CoorInstanceChip, CoorLargeChip, CoorSmallChip } from '..'

export default function ChipsExample() {
	return (
		<Box
			display={'flex'}
			flexDirection={'column'}
			gap={2}
		>
			<Box
				display={'flex'}
				gap={1}
			>
				<CoorSmallChip
					size="md"
					text={'99+'}
				/>
				<CoorSmallChip
					size="sm"
					text={'99+'}
				/>
				<CoorSmallChip
					size="xs"
					text={'99+'}
				/>
			</Box>
			<Box
				display={'flex'}
				gap={1}
			>
				<CoorLargeChip
					size={'xl'}
					color={'yellow'}
					contrast={'high'}
					variant={'100%'}
					iconName={'help'}
					text={'hola'}
				/>
				<CoorLargeChip
					size={'lg'}
					color={'green'}
					contrast={'high'}
					variant={'100%'}
					iconName={'help'}
					text={'hola'}
				/>
				<CoorLargeChip
					size={'md'}
					color={'blue'}
					contrast={'high'}
					variant={'100%'}
					iconName={'help'}
					text={'hola'}
				/>
				<CoorLargeChip
					size={'sm'}
					color={'red'}
					contrast={'high'}
					variant={'100%'}
					iconName={'help'}
					text={'hola'}
				/>
				<CoorLargeChip
					size={'xs'}
					color={'purple'}
					contrast={'high'}
					variant={'100%'}
					iconName={'help'}
					text={'hola'}
				/>
			</Box>
			<Box
				display={'flex'}
				gap={1}
			>
				<CoorIconChip
					size={'7xl'}
					color={'yellow'}
					contrast={'soft'}
					variant={'100%'}
					iconName={'help'}
				/>

				<CoorIconChip
					size={'xl'}
					color={'red'}
					contrast={'high'}
					variant={'100%'}
					iconName={'help'}
				/>
				<CoorIconChip
					size={'lg'}
					color={'blue'}
					contrast={'high'}
					variant={'100%'}
					iconName={'help'}
				/>
				<CoorIconChip
					size={'md'}
					color={'green'}
					contrast={'high'}
					variant={'100%'}
					iconName={'help'}
				/>
				<CoorIconChip
					size={'sm'}
					color={'purple'}
					contrast={'high'}
					variant={'100%'}
					iconName={'help'}
				/>
				<CoorIconChip
					size={'xs'}
					color={'orange'}
					contrast={'high'}
					variant={'100%'}
					iconName={'help'}
				/>
			</Box>
			<Box
				display={'flex'}
				gap={1}
			>
				<CoorInstanceChip
					size={'md'}
					color={'yellow'}
					contrast={'high'}
					variant={'100%'}
					iconName={'help'}
					text={'Instance'}
				/>
				<CoorInstanceChip
					size={'sm'}
					color={'red'}
					contrast={'high'}
					variant={'100%'}
					iconName={'help'}
					text={'Instance'}
				/>
				<CoorInstanceChip
					size={'xs'}
					color={'blue'}
					contrast={'high'}
					variant={'100%'}
					iconName={'help'}
					text={'Instance'}
				/>
			</Box>
		</Box>
	)
}
